language: python

python: 
  - '2.7'
  - '3.5'

install:
  - pip install requests
  - pip install beautifulsoup4
  - pip install pandas

script: py.test -v tests/

deploy:
  provider: pypi
  user: sports-analytics
  on:
    tags: true
    repo: sports-analytics/fifa_py

